language: node_js
node_js:
  - "4.1"
  - "0.12"
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
  # # Add a build with screenshot uploads for 0.10
  # include:
  #   - node_js: "0.10"
  #     env: UPLOAD_RESULTS="TRUE"

before_install:
  # Upgrade npm to avoid semver issues
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

  # Install node-webkit
  - ./test/utils/install-node-webkit.sh "$USER"

script:
  # Run Travis tests (upon failure, upload to imgur)
  - 'npm run test-travis || ((test "$UPLOAD_RESULTS" = "TRUE" && ./test/perceptual-tests/upload-screenshots.sh) && exit 1)'

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
