language: node_js
node_js:
  # - "0.11"
  - "0.10"
  # - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

install:
  - npm install -g underscore-cli  # TODO: Move this into a npm script
  - npm install

script:
  # Run integration tests
  - npm run test-integration

  # Run perceptual diff tests (upon failure, upload to imgur)
  - "npm run test-perceptual || (./test/perceptual-tests/upload-screenshots.sh && exit 1)"

notifications:
  email: false
