language: node_js
node_js:
  # - "0.11"
  - "0.10"
  # - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"
  # Add a build with screenshot uploads for 0.10
  include:
    - node_js: "0.10"
      env: UPLOAD_RESULTS="TRUE"

script:
  # Run integration tests
  - npm run test-integration

  # Run perceptual diff tests (upon failure, upload to imgur)
  - 'npm run test-perceptual || ((test "$UPLOAD_RESULTS" = "TRUE" && ./test/perceptual-tests/upload-screenshots.sh) && exit 1)'
  - ./test/perceptual-tests/upload-screenshots.sh

notifications:
  email: false
