language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"
  # # Add a build with screenshot uploads for 0.10
  # include:
  #   - node_js: "0.10"
  #     env: UPLOAD_RESULTS="TRUE"

before_install:
  # Upgrade npm
  - npm install npm@1.x.x -g

  # Install node-webkit
  - wget http://dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-linux-x64.tar.gz
  - tar xvf node-webkit-v0.10.5-linux-x64.tar.gz
  - sudo cp node-webkit-v0.10.5-linux-x64 /usr/local/lib/node-webkit/ -R
  - chown "$USER" -R /usr/local/lib/node-webkit/ -R
  - sudo ln -s /usr/local/lib/node-webkit/nw /usr/local/bin/nw

script:
  # # Run integration tests
  # - npm run test-integration

  # Run perceptual diff tests (upon failure, upload to imgur)
  - 'npm run test-perceptual || ((test "$UPLOAD_RESULTS" = "TRUE" && ./test/perceptual-tests/upload-screenshots.sh) && exit 1)'

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
